jaffle_postgres:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5432
      dbname: jaffle
      schema: analytics
      threads: 4
      keepalives_idle: 0
