version: 2

models:
  # Staging Models: Clean and standardize Olist raw data
  - name: stg_olist_customers
    description: Staged customer data from Olist dataset. Contains customer location information.
    columns:
      - name: customer_id
        description: Unique customer identifier
        tests: [not_null, unique]
      - name: customer_unique_id
        description: Unique customer identifier across the platform
        tests: [not_null]
      - name: customer_city
        description: Customer's city
      - name: customer_state
        description: Customer's state
      - name: customer_zip_code_prefix
        description: Customer's zip code prefix

  - name: stg_olist_orders
    description: Staged order data from Olist dataset. Contains order status and timestamps.
    columns:
      - name: order_id
        description: Unique order identifier
        tests: [not_null, unique]
      - name: customer_id
        description: Foreign key to customer
        tests: [not_null]
      - name: order_status
        description: Current order status
        tests: [not_null]
      - name: order_purchase_ts
        description: Timestamp when order was purchased
        tests: [not_null]

  - name: stg_olist_payments
    description: Staged payment data from Olist dataset. Contains payment details per order.
    columns:
      - name: order_id
        description: Foreign key to order
        tests: [not_null]
      - name: payment_sequential
        description: Sequential number of payment for the order
      - name: payment_type
        description: Payment method type
      - name: payment_value
        description: Payment amount
        tests: [not_null]

  - name: stg_olist_order_items
    description: Staged order items data from Olist dataset. Line items for each order.
    columns:
      - name: order_id
        description: Foreign key to order
        tests: [not_null]

  # Mart Models: Business-ready dimensional and fact tables
  - name: dim_customer
    description: Customer dimension table for Olist data. Contains customer location attributes.
    columns:
      - name: customer_id
        description: Unique customer identifier
        tests: [not_null, unique]
      - name: customer_unique_id
        description: Unique customer identifier across platform
      - name: customer_city
        description: Customer's city
      - name: customer_state
        description: Customer's state
      - name: customer_zip_code_prefix
        description: Customer's zip code prefix

  - name: fact_orders
    description: Order fact table for Olist data. Contains order events with aggregated payment totals.
    columns:
      - name: order_id
        description: Unique order identifier
        tests: [not_null, unique]
      - name: customer_id
        description: Foreign key to dim_customer
        tests: [not_null]
      - name: order_date
        description: Date/time when order was placed
        tests: [not_null]
      - name: status
        description: Current order status
        tests: [not_null]
      - name: total_amount
        description: Total payment amount for the order
        tests: [not_null]

  # Aggregate Mart Models: Business metrics and KPIs
  - name: monthly_revenue
    description: Monthly revenue metrics from Olist orders. Aggregates total order amounts by month.
    columns:
      - name: revenue_month
        description: First day of the month (date)
        tests: [not_null, unique]
      - name: revenue
        description: Total revenue for the month
        tests: [not_null]

  - name: top_customers
    description: Customer ranking by lifetime spend from Olist data. Shows cumulative order value and location.
    columns:
      - name: customer_id
        description: Unique customer identifier
        tests: [not_null]
      - name: customer_unique_id
        description: Unique customer identifier across platform
      - name: customer_city
        description: Customer's city
      - name: customer_state
        description: Customer's state
      - name: total_spend
        description: Total lifetime spend across all orders
        tests: [not_null]
      - name: order_count
        description: Total number of orders placed by customer
        tests: [not_null]
      - name: spend_rank
        description: Rank of customer by total spend (1 = highest spend)
        tests: [not_null, unique]

  - name: cancellation_rate
    description: Monthly cancellation analysis for Olist orders. Tracks order cancellations and rates.
    columns:
      - name: cancellation_month
        description: First day of the month (date)
        tests: [not_null, unique]
      - name: total_orders
        description: Total number of orders in the month
        tests: [not_null]
      - name: cancelled_orders
        description: Number of cancelled orders in the month
        tests: [not_null]
      - name: cancellation_rate_pct
        description: Cancellation rate as percentage (0-100)
        tests: [not_null]
